version: "3.9"
services:
  bot:
    build: .
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - RANDOM_ORG_API_KEY=${RANDOM_ORG_API_KEY}
      - ConnectionStrings__DefaultConnection=Server=db.qnkpbcxmmbdbhsldvvzc.supabase.co;Port=5432;Username=postgres;Password=${SUPABASE_DB_PW};Database=postgres;


    # depends_on:
      # - db
    restart: unless-stopped
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: botdb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  pgdata:
